version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bazaar_db
    volumes:
      - ../database/postgres_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    driver: local
